package ClinicServerIDLInterface;


/**
* ClinicServerIDLInterface/ClinicServerIDLInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServerIDLInterface.idl
* Tuesday, July 5, 2016 8:10:22 PM ADT
*/

public interface ClinicServerIDLInterface extends ClinicServerIDLInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClinicServerIDLInterface
