package ClinicServerIDLInterface;

/**
* ClinicServerIDLInterface/ClinicServerIDLInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServerIDLInterface.idl
* Tuesday, July 5, 2016 8:10:22 PM ADT
*/

public final class ClinicServerIDLInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ClinicServerIDLInterface value = null;

  public ClinicServerIDLInterfaceHolder ()
  {
  }

  public ClinicServerIDLInterfaceHolder (ClinicServerIDLInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClinicServerIDLInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClinicServerIDLInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClinicServerIDLInterfaceHelper.type ();
  }

}
