package ClinicServerIDLInterface;


/**
* ClinicServerIDLInterface/ClinicServerIDLInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServerIDLInterface.idl
* Tuesday, July 5, 2016 8:10:22 PM ADT
*/

public interface ClinicServerIDLInterfaceOperations 
{
  boolean managerAuthentication (String managerID);
  boolean createDRecord (String fName, String lName, String add, String phn, String spclztn, String loc);
  boolean createNRecord (String fName, String lName, String desig, String stat_Date, String stat);
  boolean editRecord (String recordID, String fieldName, String newValue);
  int getCount (String recordType);
  boolean transferRecord (String managerID, String recordID, String location);
} // interface ClinicServerIDLInterfaceOperations
